name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Executa a pipeline apenas quando houver alterações na pasta backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar Deploy via SSH na EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dashboard-financeira/backend
            git pull origin main
            npm install
            npm run build
            pm2 restart financas-api